/**
 * Dev-time script: generate the static KYC trace datasets.
 * Run:  node scripts/buildKycTraces.mjs
 * Outputs: src/data/kycTraces.js
 */
import { generateTraceSet, computeFlowStats } from '../src/data/kycTraceGenerator.js'
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Dec 2025 (3 months ago): 287 applications
// 172 US / 115 non-US, 264 approved / 23 escalated
const decemberTraces = generateTraceSet({
  seed: 'kyc-baseline-dec-2025',
  usApproved: 165,
  usEscalated: 7,
  nonUsApproved: 99,
  nonUsEscalated: 16,
})

// Jan 2026 (2 months ago): 320 applications
// 190 US / 130 non-US, 272 approved / 48 escalated
const januaryTraces = generateTraceSet({
  seed: 'kyc-january-jan-2026',
  usApproved: 185,
  usEscalated: 5,
  nonUsApproved: 87,
  nonUsEscalated: 43,
})

// Feb 2026 (current): 362 applications
// 212 US / 150 non-US, 279 approved / 83 escalated
const februaryTraces = generateTraceSet({
  seed: 'kyc-current-feb-2026',
  usApproved: 202,
  usEscalated: 10,
  nonUsApproved: 77,
  nonUsEscalated: 73,
})

// Verify counts
const dStats = computeFlowStats(decemberTraces)
const jStats = computeFlowStats(januaryTraces)
const fStats = computeFlowStats(februaryTraces)

console.log('December stats:', JSON.stringify(dStats, null, 2))
console.log(`December total: ${dStats.nodes.application} (expected 287)`)
console.log('January stats:', JSON.stringify(jStats, null, 2))
console.log(`January total: ${jStats.nodes.application} (expected 320)`)
console.log('February stats:', JSON.stringify(fStats, null, 2))
console.log(`February total: ${fStats.nodes.application} (expected 362)`)

// Write output
const outPath = resolve(__dirname, '../src/data/kycTraces.js')
const content = `// AUTO-GENERATED by scripts/buildKycTraces.mjs — do not edit manually
// Dec 2025 (287) | Jan 2026 (320) | Feb 2026 (362)

export const decemberTraces = ${JSON.stringify(decemberTraces)}

export const januaryTraces = ${JSON.stringify(januaryTraces)}

export const februaryTraces = ${JSON.stringify(februaryTraces)}

export const tracesByWindow = {
  3: decemberTraces,
  2: januaryTraces,
  1: februaryTraces,
}
`

writeFileSync(outPath, content, 'utf-8')
console.log(`\nWrote ${outPath} (${(content.length / 1024).toFixed(0)} KB)`)
